### PR TITLE
Update ERC-20 token list and fix audit errors

### PR DESCRIPTION
**Pull request by onyb**
The package [eth-contract-metadata](https://www.npmjs.com/package/eth-contract-metadata) has been deprecated, and replaced
with [@metamask/contract-metadata](https://www.npmjs.com/package/@metamask/contract-metadata).

Fixes brave/brave-browser#15688.

## ⚠️ Update (audit fixes)

A few packages were raising audit errors (even on `master` branch), so I've fixed them in this PR. Each update is in a separate commit for posterity.

One moderate-level audit error due to `postcss` couldn't be fixed because the dependencies that rely on it don't support the new version yet. As a workaround, I have added a feature that allows specifying known audit issues in the `package.json` file. See commit 31947613523ea2f83ad4b9591ced78f457a41cfc.

### CODE REVIEW

**Review by bbondy — APPROVED** [review]

**Comment by onyb** [comment]
By the way, the build failure is unrelated to the changes in this PR. I managed to reproduce it on `master` (see [build logs](https://travis-ci.com/github/onyb/ethereum-remote-client/builds/225359940)).

I'll go through the changelog of each vulnerable dependency, and fix the audit errors in a separate commit.

**Comment by bbondy** [comment]
Adding @diracdeltas for the ` app/scripts/audit.js ` change

**Review by diracdeltas — CHANGES_REQUESTED** [review]
If possible we should specify the fixed version of `postcss` in the package.json `resolutions` field so that yarn will resolve to the fixed version regardless of what the postcss dependencies specify.

If this breaks the dependencies, I would prefer that we whitelist specific advisories instead of the entire package in `app/scripts/audit.js`, so it's easy to figure out when we can un-whitelist them. Here's an example: https://github.com/brave/brave-core/pull/8747/files#diff-a69e633bdbae5d870abc8b9c5b0086be91e75569ea3526810d107598d6df478fR33

**Comment by onyb** [comment]
> If possible we should specify the fixed version of postcss in the package.json resolutions field

Already tried this, but the `stylelint` dependency doesn't support the fixed version of `postcss`, since it has many breaking changes.

I incorporated your feedback to ignore NPM advisories by specifying the IDs in `app/scripts/audit.js`. See commit aeaaf674f.

**Review by diracdeltas — APPROVED** [review]
lgtm

**Review by bbondy — APPROVED** [review]

**Pull request merged**
