### PR TITLE
Adding warning when sending a token to its own contract address

### PR DESCRIPTION
**Pull request by ryanml**
Fixes brave/brave-browser#12959

### CODE REVIEW

**Review by bbondy — APPROVED** [review]
Possible to add a test for this?

**Comment by ryanml** [comment]
> Possible to add a test for this?

Absolutely, I’d like to do an E2E test as well as add the address comparison check to a utility and do a quick un

**Comment by ryanml** [comment]
> Possible to add a test for this?

Yep, will add an e2e 👍

**Review by marshall — APPROVED** [review]

**Comment by ryanml** [comment]
Tests added

**Review by bbondy — APPROVED** [review]

**Pull request merged**
