### PR TITLE
Add Incubed as network provider option

### PR DESCRIPTION
**Pull request by chirag-parmar**
Hi Brave Team,

Slock.it just released the first stable version of its blockchain client, IN3. Incubed, unlike Infura connects to the Ethereum Blockchain via an **IN**centivized **N**ode **N**etwork which incentivises and distributes the trust on remote nodes while still keeping the bandwidth and storage requirements low. According to our understanding Brave's CryptoWallet uses Infura as a network provider. While, Infura has its advantages it demands a high amount of trust. We at Slock.it want to change this by providing IN3 as an option into Brave's CryptoWallet through this pull request.

To know how it works, try it, or even run a node, check our [documentation](https://in3.readthedocs.io/en/develop/).

#### Functionality

* Users of CryptoWallet would just have turn the `Use In3` switch on under the `Advanced` tab of `Settings` (Settings -> Advanced -> Use In3).
* CryptoWallet will automatically change the provider to the network the user is currently using.
* In case the network is local, custom or one not supported by incubed, the user will still be connected to it until a supported network is selected on the menu.

UX/UI-IN3

#### Changes
* New dependency for IN3's rpc middleware. `eth-json-rpc-in3`
* New module Incubed network adapter
* Added 'enable Incubed network' toggle button under Settings -> Advanced
* Added a provider display in the network menu
* Hid unavailable networks on the network menu when incubed is enabled.
* Added tests for ui and modules.

#### Questions
1. This repository's `CONTRIBUTING.md` files says that all PR's must be submitted against the `develop` branch. Since you do not have a `develop` branch we have created a the PR against the `master` branch. Did we get that right?
2. The repository's CHANGELOG says **Current Develop Branch**. Shouldn't that be **Current Master Branch**? Let us know so that we can append the important changes to the CHANGELOG
3. Are there any suggestions from your side?

### CODE REVIEW

**Comment by cerealkill** [comment]
Incubed is a game changer! It is basically Casper for RPC, with portable code that runs on microcontrollers and a backend that can be attached to any running client. This is proper BUIDLR mindset, remove centralisation from every corner.

**Comment by ryanml** [comment]
Hi @chirag-parmar - thanks for submitting this and all of the hard work you've put in to it. It's certainly a neat idea, but a couple of things:

`ethereum-remote-client` exists as an up-to-date fork of `MetaMask/metamask-extension` as such, you noticed we don't modify any core files, such as in the `app/` or `ui/` directory. Rather, we contain everything within in `brave/` and having a patching system which ensures MetaMask base files are neatly overridden. This is to avoid painful upstream rebases.

I would like to suggest that you take this code, and open it up as a feature request in `MetaMask/metamask-extension` - then if it is merged in, Brave Crypto Wallets will be able to pull it in the next upstream rebase. This is our work flow for contributing large customizations to `ethereum-remote-client`, I patch upstream semi-frequently. Let me know if you have any questions. Thanks! :)

**Comment by ryanml** [comment]
Also, per the above, CONTRIBUTING.MD refers to MetaMask’s contributor guidelines.

**Comment by chirag-parmar** [comment]
Hi @ryanml, apologies for the late reply. Metamask had declined our pull request before we submitted this one. Metamask's team fails to understand the value proposition of the IN3 client. I do not know of any other client that solves the trust problems of a remote client and bandwidth problems of a light client at the same time.

At slock.it we are trying to push the community to use better alternatives to remote clients. This is because we understand the risks that come with it, especially for a wallet application. Is there absolutely no other way we can integrate the IN3 client into brave? Maybe some script wizardry. This is just one of the ideas. If we can collaborate on this I am sure we can come up with a smart solution to this problem.

That being said if you still insist that a pull request in `metamask-extension` is the only way we can integrate this into brave then I'll go ahead and close this pull request.

**Comment by marshall** [comment]
hey @chirag-parmar, just closing the loop here -- we appreciate the pull request, but we've decided not to move forward without Incubed as a network provider option in Crypto Wallets.

we are focusing all of our resources on improving Crypto Wallets as a native UX in Brave, and bringing this PR inline with our new direction isn't in the cards in the near-term.

I'm closing this PR, since we don't intend to merge it, and it looks like there hasn't been a response to this PR since May in any case

**Pull request closed without merging**
