### PR TITLE
Fixing dist build task order

### PR DESCRIPTION
**Pull request by ryanml**

### CODE REVIEW

**Comment by bbondy** [comment]
I don't think that'll matter because otherwise it'd be a race condition

**Comment by bbondy** [comment]
I think `'copy'` should be moved inside `gulpParallel` and I think we should add
`'optimize:images'`

**Comment by bbondy** [comment]
comparing https://github.com/brave/ethereum-remote-client/blob/master/gulpfile.js and https://github.com/brave/ethereum-remote-client/blob/master/brave/gulpfile.js/index.js for the build task

**Comment by ryanml** [comment]
Closing as this does not accomplish/is not related to the issue we were trying to fix

**Pull request closed without merging**
