### PR TITLE
Remove window.web3 API

### PR DESCRIPTION
**Pull request by marshall**
Updated to latest inpage-provider dependency, removing the need for our own fork.

Fixes brave/brave-browser#11703

### CODE REVIEW

**Review by ryanml — DISMISSED** [review]
this looks good to merge come november

**Review by ryanml — APPROVED** [review]
++

**Comment by bbondy** [comment]
This isn't ready yet, so reverting.  There are many breaking changes in the new inpage provider so we can't update the dep without adapting lots of code.

**Comment by bbondy** [comment]
Reverted here: https://github.com/brave/ethereum-remote-client/pull/219

**Pull request merged**
